### PR TITLE
Fix for LateInitializationError during rebuild of parent widget.

### PR DESCRIPTION
**Pull request by beattizzle**

### CODE REVIEW

**Comment by tomoyu719** [comment]
@beattizzle 
Thank you very much for your commitment and dedication.

**Comment by tomoyu719** [comment]
close #19

**Comment by lukasnalezenec** [comment]
That is interesting.  This shouldn't happen unless the Future fails. Maybe there's an issue with assets in your project setup?

To test it, you could write a simple Flutter component test to see what’s going on. Will send you some example. 

Also, I think those two fields shouldn’t be in the class, and their values should be passed into the Future instead.

`
late final GlyphPaths glyphPath;
late final GlyphMetadata metadata;
`

I fixed another issue where the load method can take up to 700 milliseconds. How long does it take in your app? It might be better to load the font info at app startup instead of during component initialization.

**Comment by lukasnalezenec** [comment]
Btw,
Check this PR
https://github.com/tomoyu719/simple_sheet_music/pull/18/commits

@tomoyu719 @beattizzle

**Pull request merged**
